Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/11/2022
Var
// Seção de Declarações das variáveis 
num1,num2,resultado:inteiro

Inicio
// Seção de Comandos, procedimento, funçõs, operadores, etc...
para num2 de 1 ate 10000 faca
escreval (num2," x 9 =",num2*9)
fimpara





Fimalgoritmo